[package]
name = "sm4test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#libsm ={git="https://github.com/citahub/libsm.git"}
libsm ={path="../libsm"}
rand = "0.8.3"
